EXE=damage_sex
CPP=main.cpp damage_sex.cpp individual.cpp patch.cpp
HPP=damage_sex.hpp individual.hpp patch.hpp parameters.hpp

CXX=g++
CXXFLAGS=-Wall -O3 -std=c++20

$(EXE) : $(CPP) $(HPP)
	$(CXX) $(CXXFLAGS) -o $(EXE) $(CPP)
